{"name": "test_ConsultationOrders[2020-03-1]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../api/api.yaml'", "trace": "cls = <class 'gm.testcase.test_api.Test_api'>\n\n    @classmethod\n    def setup_class(cls):\n>       cls.login = Testapi().login()\n\ntestcase/test_api.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\napi/api_face.py:16: in __init__\n    self.data = self.api_load(\"../api/api.yaml\")\napi/base_api.py:33: in api_load\n    return self.yaml_load(path)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ncls = <class 'gm.api.api_face.Testapi'>, path = '../api/api.yaml'\n\n    @classmethod\n    def yaml_load(cls, path) -> list:\n>       with open(path) as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../api/api.yaml'\n\napi/base_api.py:28: FileNotFoundError"}, "parameters": [{"name": "year", "value": "'2020'"}, {"name": "month", "value": "'03'"}, {"name": "page", "value": "'1'"}], "start": 1588835843111, "stop": 1588835843111, "uuid": "8fa43454-effd-4b55-9787-fa3023f111d8", "historyId": "dd5d6fbebf80723ce638dd3e35d25e3f", "testCaseId": "90072c1d28b48bbf14e9fbceea841c64", "fullName": "testcase.test_api.Test_api#test_ConsultationOrders", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "Test_api"}, {"name": "host", "value": "dengyingdeMacBook-Pro.local"}, {"name": "thread", "value": "3477-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_api"}]}